"""Drop password, add public_id to User

Revision ID: 507544a5b057
Revises: 2e96bec5114d
Create Date: 2025-08-07 22:03:46.587408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507544a5b057'
down_revision = '2e96bec5114d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
